// This file will be auto-generated by Supabase CLI
// Run: pnpm --filter @quillty/api db:types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          username: string;
          display_name: string | null;
          avatar_url: string | null;
          bio: string | null;
          is_partner: boolean;
          follower_count: number;
          following_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          username: string;
          display_name?: string | null;
          avatar_url?: string | null;
          bio?: string | null;
          is_partner?: boolean;
          follower_count?: number;
          following_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          username?: string;
          display_name?: string | null;
          avatar_url?: string | null;
          bio?: string | null;
          is_partner?: boolean;
          follower_count?: number;
          following_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      quilt_patterns: {
        Row: {
          id: string;
          creator_id: string;
          title: string;
          description: string | null;
          thumbnail_url: string | null;
          status: 'draft' | 'published_free' | 'published_premium';
          price_cents: number | null;
          difficulty: 'beginner' | 'intermediate' | 'advanced';
          category: string | null;
          size: string | null;
          design_data: Json;
          like_count: number;
          save_count: number;
          comment_count: number;
          view_count: number;
          created_at: string;
          updated_at: string;
          published_at: string | null;
        };
        Insert: {
          id?: string;
          creator_id: string;
          title: string;
          description?: string | null;
          thumbnail_url?: string | null;
          status?: 'draft' | 'published_free' | 'published_premium';
          price_cents?: number | null;
          difficulty?: 'beginner' | 'intermediate' | 'advanced';
          category?: string | null;
          size?: string | null;
          design_data: Json;
          like_count?: number;
          save_count?: number;
          comment_count?: number;
          view_count?: number;
          created_at?: string;
          updated_at?: string;
          published_at?: string | null;
        };
        Update: {
          id?: string;
          creator_id?: string;
          title?: string;
          description?: string | null;
          thumbnail_url?: string | null;
          status?: 'draft' | 'published_free' | 'published_premium';
          price_cents?: number | null;
          difficulty?: 'beginner' | 'intermediate' | 'advanced';
          category?: string | null;
          size?: string | null;
          design_data?: Json;
          like_count?: number;
          save_count?: number;
          comment_count?: number;
          view_count?: number;
          created_at?: string;
          updated_at?: string;
          published_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'quilt_patterns_creator_id_fkey';
            columns: ['creator_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          }
        ];
      };
      follows: {
        Row: {
          follower_id: string;
          followed_id: string;
          created_at: string;
        };
        Insert: {
          follower_id: string;
          followed_id: string;
          created_at?: string;
        };
        Update: {
          follower_id?: string;
          followed_id?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'follows_follower_id_fkey';
            columns: ['follower_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'follows_followed_id_fkey';
            columns: ['followed_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          }
        ];
      };
      blocks: {
        Row: {
          id: string;
          creator_id: string;
          name: string;
          description: string | null;
          thumbnail_url: string | null;
          is_platform_block: boolean;
          grid_size: number;
          design_data: Json;
          difficulty: 'beginner' | 'intermediate' | 'advanced';
          piece_count: number;
          like_count: number;
          save_count: number;
          comment_count: number;
          usage_count: number;
          status: 'draft' | 'published';
          created_at: string;
          updated_at: string;
          published_at: string | null;
        };
        Insert: {
          id?: string;
          creator_id: string;
          name: string;
          description?: string | null;
          thumbnail_url?: string | null;
          is_platform_block?: boolean;
          grid_size?: number;
          design_data: Json;
          difficulty?: 'beginner' | 'intermediate' | 'advanced';
          piece_count?: number;
          like_count?: number;
          save_count?: number;
          comment_count?: number;
          usage_count?: number;
          status?: 'draft' | 'published';
          created_at?: string;
          updated_at?: string;
          published_at?: string | null;
        };
        Update: {
          id?: string;
          creator_id?: string;
          name?: string;
          description?: string | null;
          thumbnail_url?: string | null;
          is_platform_block?: boolean;
          grid_size?: number;
          design_data?: Json;
          difficulty?: 'beginner' | 'intermediate' | 'advanced';
          piece_count?: number;
          like_count?: number;
          save_count?: number;
          comment_count?: number;
          usage_count?: number;
          status?: 'draft' | 'published';
          created_at?: string;
          updated_at?: string;
          published_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'blocks_creator_id_fkey';
            columns: ['creator_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          }
        ];
      };
      likes: {
        Row: {
          id: string;
          user_id: string;
          pattern_id: string | null;
          block_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          pattern_id?: string | null;
          block_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          pattern_id?: string | null;
          block_id?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'likes_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'likes_pattern_id_fkey';
            columns: ['pattern_id'];
            isOneToOne: false;
            referencedRelation: 'quilt_patterns';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'likes_block_id_fkey';
            columns: ['block_id'];
            isOneToOne: false;
            referencedRelation: 'blocks';
            referencedColumns: ['id'];
          }
        ];
      };
      saves: {
        Row: {
          id: string;
          user_id: string;
          pattern_id: string | null;
          block_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          pattern_id?: string | null;
          block_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          pattern_id?: string | null;
          block_id?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'saves_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'saves_pattern_id_fkey';
            columns: ['pattern_id'];
            isOneToOne: false;
            referencedRelation: 'quilt_patterns';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'saves_block_id_fkey';
            columns: ['block_id'];
            isOneToOne: false;
            referencedRelation: 'blocks';
            referencedColumns: ['id'];
          }
        ];
      };
      comments: {
        Row: {
          id: string;
          user_id: string;
          pattern_id: string | null;
          block_id: string | null;
          content: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          pattern_id?: string | null;
          block_id?: string | null;
          content: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          pattern_id?: string | null;
          block_id?: string | null;
          content?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'comments_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'comments_pattern_id_fkey';
            columns: ['pattern_id'];
            isOneToOne: false;
            referencedRelation: 'quilt_patterns';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'comments_block_id_fkey';
            columns: ['block_id'];
            isOneToOne: false;
            referencedRelation: 'blocks';
            referencedColumns: ['id'];
          }
        ];
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          type: 'like' | 'comment' | 'follow' | 'purchase' | 'payout';
          actor_id: string | null;
          pattern_id: string | null;
          block_id: string | null;
          read: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: 'like' | 'comment' | 'follow' | 'purchase' | 'payout';
          actor_id?: string | null;
          pattern_id?: string | null;
          block_id?: string | null;
          read?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          type?: 'like' | 'comment' | 'follow' | 'purchase' | 'payout';
          actor_id?: string | null;
          pattern_id?: string | null;
          block_id?: string | null;
          read?: boolean;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'notifications_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'notifications_actor_id_fkey';
            columns: ['actor_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          }
        ];
      };
      partners: {
        Row: {
          id: string;
          user_id: string;
          stripe_account_id: string | null;
          stripe_onboarding_complete: boolean;
          status: 'pending' | 'active' | 'suspended';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          stripe_account_id?: string | null;
          stripe_onboarding_complete?: boolean;
          status?: 'pending' | 'active' | 'suspended';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          stripe_account_id?: string | null;
          stripe_onboarding_complete?: boolean;
          status?: 'pending' | 'active' | 'suspended';
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'partners_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: true;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          }
        ];
      };
      purchases: {
        Row: {
          id: string;
          user_id: string;
          pattern_id: string;
          stripe_payment_intent_id: string;
          amount_cents: number;
          platform_fee_cents: number;
          creator_payout_cents: number;
          status: 'pending' | 'completed' | 'refunded';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          pattern_id: string;
          stripe_payment_intent_id: string;
          amount_cents: number;
          platform_fee_cents: number;
          creator_payout_cents: number;
          status?: 'pending' | 'completed' | 'refunded';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          pattern_id?: string;
          stripe_payment_intent_id?: string;
          amount_cents?: number;
          platform_fee_cents?: number;
          creator_payout_cents?: number;
          status?: 'pending' | 'completed' | 'refunded';
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'purchases_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'purchases_pattern_id_fkey';
            columns: ['pattern_id'];
            isOneToOne: false;
            referencedRelation: 'quilt_patterns';
            referencedColumns: ['id'];
          }
        ];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};

type PublicSchema = Database[Extract<keyof Database, 'public'>];

export type Tables<
  PublicTableNameOrOptions extends
    | keyof (PublicSchema['Tables'] & PublicSchema['Views'])
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof (Database[PublicTableNameOrOptions['schema']]['Tables'] &
        Database[PublicTableNameOrOptions['schema']]['Views'])
    : never = never
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? (Database[PublicTableNameOrOptions['schema']]['Tables'] &
      Database[PublicTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : PublicTableNameOrOptions extends keyof (PublicSchema['Tables'] &
        PublicSchema['Views'])
    ? (PublicSchema['Tables'] &
        PublicSchema['Views'])[PublicTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  PublicTableNameOrOptions extends
    | keyof PublicSchema['Tables']
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicTableNameOrOptions['schema']]['Tables']
    : never = never
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? Database[PublicTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : PublicTableNameOrOptions extends keyof PublicSchema['Tables']
    ? PublicSchema['Tables'][PublicTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  PublicTableNameOrOptions extends
    | keyof PublicSchema['Tables']
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicTableNameOrOptions['schema']]['Tables']
    : never = never
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? Database[PublicTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : PublicTableNameOrOptions extends keyof PublicSchema['Tables']
    ? PublicSchema['Tables'][PublicTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;
